/**
 * config.js — 静态配置
 *
 * 职责：集中管理所有"硬编码"的业务常量。
 * 扩展方法：
 *   - 新增 Tab 页：在 TABS 数组里加一条记录，panel 字段指向 ui.js 里的渲染函数。
 *   - 新增会员枠：在 FRAME_KEYS / FRAME_LABELS / FRAME_BADGE 里同步添加。
 *   - 新增默认成员：在 DEFAULT_MEMBERS 里追加对象。
 */

/* ── Tab 导航定义 ─────────────────────────────────────────────
   panel 字段是函数引用，在 app.js 初始化后用实际函数填充。
   这里先用字符串占位，app.js 会在 DOMContentLoaded 后替换。       */
const TABS = [
  { id: 'members',     labelKey: 'nav_members', icon: '👤' },
  { id: 'audiences',   labelKey: 'nav_audiences', icon: '👥' },
  { id: 'performance', labelKey: 'nav_performance', icon: '🎭' },
  { id: 'lottery_cfg', labelKey: 'nav_lottery_cfg', icon: '⚙️' },
  { id: 'run',         labelKey: 'nav_run', icon: '🎯' },
];

/* ── 会员枠常量 ──────────────────────────────────────────────
   FRAME_KEYS 决定枠的顺序，其他 Map 用 key 对应显示信息。        */
const FRAME_KEYS = [
  '映像倉庫',
  '柱の会',
  '百発98中',
  '女性小中学生',
  'ファミリーカップル',
];

/** 枠 key → 显示名称（用于表单 label） */
const FRAME_LABELS = {
  '映像倉庫':          '映像倉庫会員枠',
  '柱の会':            '柱の会 会員枠',
  '百発98中':          '100発98中権利',
  '女性小中学生':       '女性・小中学生枠',
  'ファミリーカップル':  'ファミリー・カップル枠',
};

/** 枠 key → CSS badge 类名（用于徽章颜色） */
const FRAME_BADGE = {
  '映像倉庫':          'badge-purple',
  '柱の会':            'badge-blue',
  '百発98中':          'badge-amber',
  '女性小中学生':       'badge-pink',
  'ファミリーカップル':  'badge-green',
  '一般':              'badge-gray',
};

/** 随机生成观众时，会员类型的权重池（空字符串=一般观众，出现频率越高比例越大） */
const RANDOM_MEMBER_TYPE_POOL = [
  '', '', '', '', '',          // 50% 一般
  '映像倉庫',                   // 10%
  '柱の会',                     // 10%
  '百発98中',                   // 10%
  '女性小中学生',                // 10%
  'ファミリーカップル',           // 10%
];

/** 随机生成观众时，性别的权重池 */
const RANDOM_GENDER_POOL = [
  'male', 'male', 'male', 'male',   // ~50% 男性
  'female', 'female', 'female',     // ~37% 女性
  'other',                           // ~13% その他
];

/** 载入默认成员时使用的数据 */
const DEFAULT_MEMBERS = [
  { name: '岩立沙穂', priority: 5, fanCount: 850, generation: '13期生' },
  { name: '福岡聖菜',   priority: 5, fanCount: 720, generation: '15期生' },
  { name: '向井地美音', priority: 5, fanCount: 610, generation: '15期生' },
  { name: '小栗有以', priority: 5, fanCount: 680, generation: 'Team8' },
  { name: '行天優莉奈',priority: 5, fanCount: 590, generation: 'Team8' },
  { name: '倉野尾成美', priority: 5, fanCount: 420, generation: 'Team8' },
  { name: '坂川陽香',priority: 5, fanCount: 380, generation: 'Team8' },
  { name: '下尾みう', priority: 5, fanCount: 310, generation: 'Team8' },
  { name: '髙橋彩音', priority: 5, fanCount: 850, generation: 'Team8' },
  { name: '徳永羚海',   priority: 5, fanCount: 720, generation: 'Team8' },
  { name: '永野芹佳', priority: 5, fanCount: 610, generation: 'Team8' },
  { name: '橋本陽菜', priority: 5, fanCount: 680, generation: 'Team8' },
  { name: '千葉恵里',priority: 5, fanCount: 590, generation: 'ドラフト2期生' },
  { name: '黒須遥香', priority: 5, fanCount: 420, generation: '16期生' },
  { name: '鈴木くるみ',priority: 5, fanCount: 380, generation: '16期生' },
  { name: '田口愛佳', priority: 5, fanCount: 310, generation: '16期生' },
  { name: '長友彩海', priority: 5, fanCount: 850, generation: '16期生' },
  { name: '武藤小麟',   priority: 5, fanCount: 720, generation: '16期生' },
  { name: '山内瑞葵', priority: 5, fanCount: 610, generation: '16期生' },
  { name: '山根涼羽', priority: 5, fanCount: 680, generation: '16期生' },
  { name: '大盛真歩',priority: 5, fanCount: 590, generation: 'ドラフト3期生' },
  { name: '太田有紀', priority: 5, fanCount: 420, generation: '17期生' },
  { name: '佐藤綺星',priority: 5, fanCount: 380, generation: '17期生' },
  { name: '橋本恵理子', priority: 5, fanCount: 310, generation: '17期生' },
  { name: '畠山希美', priority: 5, fanCount: 850, generation: '17期生' },
  { name: '平田侑希',   priority: 5, fanCount: 720, generation: '17期生' },
  { name: '布袋百椛', priority: 5, fanCount: 610, generation: '17期生' },
  { name: '正鋳真優', priority: 5, fanCount: 680, generation: '17期生' },
  { name: '水島美結',priority: 5, fanCount: 590, generation: '17期生' },
  { name: '山﨑空', priority: 5, fanCount: 420, generation: '17期生' },
  { name: '秋山由奈',priority: 5, fanCount: 380, generation: '18期生' },
  { name: '新井彩永', priority: 5, fanCount: 310, generation: '18期生' },
  { name: '工藤華純', priority: 5, fanCount: 850, generation: '18期生' },
  { name: '久保姫菜乃',   priority: 5, fanCount: 720, generation: '18期生' },
  { name: '迫由芽実', priority: 5, fanCount: 610, generation: '18期生' },
  { name: '成田香姫奈', priority: 5, fanCount: 680, generation: '18期生' },
  { name: '八木愛月',priority: 5, fanCount: 590, generation: '18期生' },
  { name: '山口結愛', priority: 5, fanCount: 420, generation: '18期生' },
  { name: '伊藤百花',priority: 5, fanCount: 380, generation: '19期生' },
  { name: '奥本カイリ', priority: 5, fanCount: 310, generation: '19期生' },
  { name: '川村結衣', priority: 5, fanCount: 850, generation: '19期生' },
  { name: '白鳥沙怜',   priority: 5, fanCount: 720, generation: '19期生' },
  { name: '花田藍衣', priority: 5, fanCount: 610, generation: '19期生' },
  { name: '大賀彩姫', priority: 5, fanCount: 680, generation: '20期研究生' },
  { name: '近藤沙樹',priority: 5, fanCount: 590, generation: '20期研究生' },
  { name: '丸山ひなた', priority: 5, fanCount: 420, generation: '20期研究生' },
  { name: '髙橋舞桜',priority: 5, fanCount: 380, generation: '21期研究生' },
  { name: '田中沙友利', priority: 5, fanCount: 310, generation: '21期研究生' },
  { name: '牧戸愛茉', priority: 5, fanCount: 850, generation: '21期研究生' },
  { name: '森川優',   priority: 5, fanCount: 720, generation: '21期研究生' },
  { name: '渡邉葵心', priority: 5, fanCount: 610, generation: '21期研究生' },
];

/** 会员枠 select 下拉选项（含"一般"） */
const MEMBER_TYPE_OPTIONS = [
  { value: '',                   label: '一般（非会員）'        },
  { value: '映像倉庫',           label: '映像倉庫会員'          },
  { value: '柱の会',             label: '柱の会 会員'           },
  { value: '百発98中',           label: '100発98中権利'         },
  { value: '女性小中学生',        label: '女性・小中学生枠'      },
  { value: 'ファミリーカップル',   label: 'ファミリー・カップル枠' },
];

const I18N = {
  zh: {
    // 导航
    nav_members:     '成员设置',
    nav_audiences:   '观众管理',
    nav_performance: '公演设置',
    nav_lottery_cfg: '抽选配置',
    nav_run:         '执行抽选',

    // 成员设置
    members_title:       '成员设置',
    members_subtitle:    'MEMBER CONFIGURATION',
    members_load_default:'载入默认成员',
    members_add_card:    '添加成员',
    members_name:        '成员名称',
    members_name_ph:     '例：橋本陽菜',
    members_priority:    '优先度',
    members_priority_tip:'1–10，影响该成员饭的抽选权重',
    members_fancount:    '饭人数',
    members_fancount_tip:'用于随机生成观众时按比例分配',
    members_generation:  '期别/队伍',
    members_generation_ph:'16期 / Team8',
    members_add_btn:     '＋ 添加成员',
    members_list:        '成员列表',
    members_clear:       '清空',
    members_th_no:       '#',
    members_th_name:     '姓名',
    members_th_priority: '优先度',
    members_th_fancount: '饭人数',
    members_th_gen:      '期别',
    members_th_action:   '操作',
    members_delete:      '削除',
    members_empty:       '暂无成员，请添加或载入默认成员',

    // 观众管理
    audiences_title:      '观众管理',
    audiences_subtitle:   'AUDIENCE DATABASE',
    audiences_clear:      '清空',
    audiences_total:      '总观众数',
    audiences_members:    '会员数',
    audiences_female:     '女性观众',
    audiences_avg_spend:  '平均消费',
    gen_card_title:       '批量生成观众',
    gen_total:            '生成总数',
    gen_frame_title:      '会员枠分配（人数）',
    gen_frame_tip:        '留空或0则不生成该枠，剩余自动分配为一般观众',
    gen_gender_title:     '性别比例',
    gen_male:             '男性',
    gen_female:           '女性',
    gen_gender_tip:       '%（其余为その他）',
    gen_age_title:        '年龄分布',
    gen_age_min:          '最小年龄',
    gen_age_max:          '最大年龄',
    gen_age_skew:         '年轻偏向',
    gen_age_skew_tip:     '（0=均匀分布，10=强烈偏年轻）',
    gen_spend_title:      '消费金额分布',
    gen_spend_min:        '最低',
    gen_spend_max:        '最高',
    gen_spend_skew:       '低消费偏向',
    gen_spend_skew_tip:   '（0=均匀，10=强烈偏低消费）',
    gen_hs_title:         '握手会消费',
    gen_hs_count:         '购买人数',
    gen_hs_count_tip:     '人（0=不生成）',
    gen_hs_range:         '金额范围',
    gen_lt_title:         '摇奖消费',
    gen_lt_count:         '参加人数',
    gen_lt_place:         '消费场所',
    gen_lt_place_theater: '劇場内',
    gen_lt_place_handshake:'握手会現場',
    gen_lt_place_online:  'オンライン',
    gen_lt_range:         '金额范围',
    gen_btn:              '随机生成',
    gen_btn_tip:          '剩余名额按成员饭人数比例分配推し',
    manual_add_title:     '＋ 手动添加单个观众',
    aud_id:               '账号 ID',
    aud_gender:           '性别',
    aud_gender_male:      '男性',
    aud_gender_female:    '女性',
    aud_gender_other:     'その他',
    aud_age:              '年龄',
    aud_membertype:       '会员类型',
    aud_membertype_none:  '一般（非会員）',
    aud_membertype_tip:   '按住 Ctrl/Cmd 可多选，不选任何项则为一般观众',
    aud_spend:            '消费金额',
    aud_spend_tip:        '円（总消费）',
    aud_reg:              '注册日期',
    aud_fav:              '最喜欢成员',
    aud_fav_none:         '（未设定）',
    aud_targets:          '消费目标',
    aud_targets_ph:       '橋本陽菜:5000,岡部麟:3000',
    aud_targets_tip:      '成员:金额，逗号分隔',
    aud_intheater:        '曾在剧场内有过消费',
    aud_lastwin:          '上次中签',
    aud_lastwin_ph:       '2024-03-15（未中签留空）',
    aud_add_btn:          '＋ 添加',
    aud_list_title:       '观众列表',
    aud_list_tip:         '(显示前100条)',
    aud_export:           '导出CSV',
    aud_th_id:            'ID',
    aud_th_gender_age:    '性别/年龄',
    aud_th_member:        '会员',
    aud_th_spend:         '消费',
    aud_th_fav:           '推し',
    aud_th_lastwin:       '最後当選',
    aud_th_intheater:     '剧場消費',
    aud_empty:            '暂无观众数据，请生成或手动添加',
    aud_show_limit:       '只显示前100条，共',
    aud_show_limit2:      '人',
    aud_general:          '一般',
    aud_not_won:          '未当選',

    // 公演设置
    perf_title:           '公演设置',
    perf_subtitle:        'PERFORMANCE CONFIGURATION',
    perf_save:            '保存设置',
    perf_basic:           '基本信息',
    perf_name:            '公演名称',
    perf_name_ph:         'チームBコンサート',
    perf_date:            '公演日期',
    perf_date_ph:         '2025-06-01',
    perf_capacity:        '席数（总）',
    perf_capacity_unit:   '席',
    perf_price:           '票价',
    perf_price_unit:      '円',
    perf_frames:          '会员枠席数',
    perf_frames_tip:      '各枠专用名额（超出枠限的同类会员进入一般枠）',
    perf_frames_unit:     '席',
    perf_members_title:   '参演成员',
    perf_members_tip:     '点击选择本次公演的参演成员，未选择任何人时抽选不考虑成员偏好权重',
    perf_members_empty:   '请先在成员设置中添加成员',
    perf_pri_title:       '本次公演优先度覆盖',
    perf_pri_tip:         '留空则使用成员全局优先度，填入数值后仅对本次公演生效',
    perf_pri_global:      '全局:',
    perf_pri_hint:        '请先在上方选择参演成员',
    perf_saved:           '公演设置已保存',

    // 抽选配置
    lcfg_title:           '抽选配置',
    lcfg_subtitle:        'LOTTERY WEIGHT SETTINGS',
    lcfg_audience_title:  '观众当选权重因子',
    lcfg_audience_tip:    '各因子对观众中签概率的加成强度（0 = 无影响，10 = 最强加成）',
    lcfg_w_gender:        '女性加权',
    lcfg_w_age:           '年轻加权（未满25岁）',
    lcfg_w_member:        '会员枠综合加权',
    lcfg_w_lastwin:       '久未中签加权',
    lcfg_w_consumption:   '消费金额加权',
    lcfg_member_title:    '成员饭权重',
    lcfg_member_tip:      '推しが参演时的额外加成',
    lcfg_w_priority:      '成员优先度权重',
    lcfg_w_fancount:      '饭人数权重',
    lcfg_frame_title:     '各会员枠倍率',
    lcfg_frame_tip:       '该枠内观众的基础权重乘数（1–20倍）',
    lcfg_overflow_title:  '枠溢出设置',
    lcfg_overflow_label:  '允许枠溢出分配',
    lcfg_overflow_tip:    '当某枠报名人数不足席数时，多余名额自动分配给一般枠，避免座位空置',

    // 执行抽选
    run_title:            '执行抽选',
    run_subtitle:         'RUN LOTTERY',
    run_applicants:       '报名人数',
    run_seats:            '总席数',
    run_frame_seats:      '会員枠席数',
    run_base_rate:        '基础中签率',
    run_confirm_title:    '公演信息确认',
    run_no_name:          '（未命名）',
    run_no_date:          '日期未设定',
    run_general:          '一般枠',
    run_issues_audiences: '观众数据为空',
    run_issues_capacity:  '公演席数未设定',
    run_start:            '▶ 开始抽选',
    run_result_title:     '抽选结果概览',
    run_winners:          '当选人数',
    run_losers:           '落选人数',
    run_rate:             '实际中签率',
    run_female_won:       '女性当选',
    run_frame_dist:       '枠分布',
    run_member_dist:      '推し成员分布（当选）',
    run_list_title:       '当选名单',
    run_list_tip:         '(前100条)',
    run_export_winners:   '导出当选CSV',
    run_export_losers:    '导出落选CSV',
    run_th_id:            'ID',
    run_th_frame:         '枠',
    run_th_gender_age:    '性别/年龄',
    run_th_member:        '会员',
    run_th_fav:           '推し',
    run_th_spend:         '消费',
    gender_male:          '男',
    gender_female:        '女',
    gender_other:         '他',
  },

  ja: {
    // 导航
    nav_members:     'メンバー設定',
    nav_audiences:   '観客管理',
    nav_performance: '公演設定',
    nav_lottery_cfg: '抽選設定',
    nav_run:         '抽選実行',

    // 成员设置
    members_title:       'メンバー設定',
    members_subtitle:    'MEMBER CONFIGURATION',
    members_load_default:'デフォルト読み込み',
    members_add_card:    'メンバー追加',
    members_name:        'メンバー名',
    members_name_ph:     '例：橋本陽菜',
    members_priority:    '優先度',
    members_priority_tip:'1–10、このメンバーのファン当選重みに影響',
    members_fancount:    'ファン数',
    members_fancount_tip:'ランダム生成時の推し配分比率に使用',
    members_generation:  '期/チーム',
    members_generation_ph:'16期 / Team8',
    members_add_btn:     '＋ メンバー追加',
    members_list:        'メンバー一覧',
    members_clear:       'クリア',
    members_th_no:       '#',
    members_th_name:     '名前',
    members_th_priority: '優先度',
    members_th_fancount: 'ファン数',
    members_th_gen:      '期/チーム',
    members_th_action:   '操作',
    members_delete:      '削除',
    members_empty:       'メンバーがいません。追加またはデフォルト読み込みをしてください',

    // 观众管理
    audiences_title:      '観客管理',
    audiences_subtitle:   'AUDIENCE DATABASE',
    audiences_clear:      'クリア',
    audiences_total:      '総観客数',
    audiences_members:    '会員数',
    audiences_female:     '女性観客',
    audiences_avg_spend:  '平均消費',
    gen_card_title:       '観客一括生成',
    gen_total:            '生成総数',
    gen_frame_title:      '会員枠配分（人数）',
    gen_frame_tip:        '0または空欄の枠は生成しません。残りは一般観客として配分されます',
    gen_gender_title:     '性別比率',
    gen_male:             '男性',
    gen_female:           '女性',
    gen_gender_tip:       '%（残りはその他）',
    gen_age_title:        '年齢分布',
    gen_age_min:          '最小年齢',
    gen_age_max:          '最大年齢',
    gen_age_skew:         '若年層偏重',
    gen_age_skew_tip:     '（0=均一、10=強く若年層寄り）',
    gen_spend_title:      '消費金額分布',
    gen_spend_min:        '最低',
    gen_spend_max:        '最高',
    gen_spend_skew:       '低消費偏重',
    gen_spend_skew_tip:   '（0=均一、10=強く低消費寄り）',
    gen_hs_title:         '握手会消費',
    gen_hs_count:         '購入人数',
    gen_hs_count_tip:     '人（0=生成しない）',
    gen_hs_range:         '金額範囲',
    gen_lt_title:         '摇奖消費',
    gen_lt_count:         '参加人数',
    gen_lt_place:         '消費場所',
    gen_lt_place_theater: '劇場内',
    gen_lt_place_handshake:'握手会現場',
    gen_lt_place_online:  'オンライン',
    gen_lt_range:         '金額範囲',
    gen_btn:              'ランダム生成',
    gen_btn_tip:          '残枠はファン数比率に応じて推しを配分',
    manual_add_title:     '＋ 観客を手動で追加',
    aud_id:               'アカウントID',
    aud_gender:           '性別',
    aud_gender_male:      '男性',
    aud_gender_female:    '女性',
    aud_gender_other:     'その他',
    aud_age:              '年齢',
    aud_membertype:       '会員種別',
    aud_membertype_none:  '一般（非会員）',
    aud_membertype_tip:   'Ctrl/Cmd を押しながら複数選択可、未選択は一般観客',
    aud_spend:            '消費金額',
    aud_spend_tip:        '円（総消費）',
    aud_reg:              '登録日',
    aud_fav:              '推しメンバー',
    aud_fav_none:         '（未設定）',
    aud_targets:          '消費目標',
    aud_targets_ph:       '橋本陽菜:5000,岡部麟:3000',
    aud_targets_tip:      'メンバー:金額、カンマ区切り',
    aud_intheater:        '劇場内で消費したことがある',
    aud_lastwin:          '最終当選日',
    aud_lastwin_ph:       '2024-03-15（未当選は空欄）',
    aud_add_btn:          '＋ 追加',
    aud_list_title:       '観客一覧',
    aud_list_tip:         '(先頭100件を表示)',
    aud_export:           'CSVエクスポート',
    aud_th_id:            'ID',
    aud_th_gender_age:    '性別/年齢',
    aud_th_member:        '会員',
    aud_th_spend:         '消費',
    aud_th_fav:           '推し',
    aud_th_lastwin:       '最終当選',
    aud_th_intheater:     '劇場消費',
    aud_empty:            '観客データがありません。生成または手動追加してください',
    aud_show_limit:       '先頭100件のみ表示、全',
    aud_show_limit2:      '人',
    aud_general:          '一般',
    aud_not_won:          '未当選',

    // 公演设置
    perf_title:           '公演設定',
    perf_subtitle:        'PERFORMANCE CONFIGURATION',
    perf_save:            '設定を保存',
    perf_basic:           '基本情報',
    perf_name:            '公演名',
    perf_name_ph:         'チームBコンサート',
    perf_date:            '公演日',
    perf_date_ph:         '2025-06-01',
    perf_capacity:        '席数（合計）',
    perf_capacity_unit:   '席',
    perf_price:           'チケット価格',
    perf_price_unit:      '円',
    perf_frames:          '会員枠席数',
    perf_frames_tip:      '各枠の専用席数（枠を超えた同種会員は一般枠へ）',
    perf_frames_unit:     '席',
    perf_members_title:   '出演メンバー',
    perf_members_tip:     'クリックして出演メンバーを選択。未選択の場合、推し偏重は無効になります',
    perf_members_empty:   '先にメンバー設定でメンバーを追加してください',
    perf_pri_title:       '今回公演の優先度上書き',
    perf_pri_tip:         '空欄はグローバル優先度を使用。入力値は今回の公演のみ有効',
    perf_pri_global:      'グローバル:',
    perf_pri_hint:        '先に出演メンバーを選択してください',
    perf_saved:           '公演設定を保存しました',

    // 抽选配置
    lcfg_title:           '抽選設定',
    lcfg_subtitle:        'LOTTERY WEIGHT SETTINGS',
    lcfg_audience_title:  '観客当選重みファクター',
    lcfg_audience_tip:    '各ファクターの当選確率への加算強度（0=影響なし、10=最大加算）',
    lcfg_w_gender:        '女性加重',
    lcfg_w_age:           '若年加重（25歳未満）',
    lcfg_w_member:        '会員枠総合加重',
    lcfg_w_lastwin:       '長期未当選加重',
    lcfg_w_consumption:   '消費金額加重',
    lcfg_member_title:    'ファン重み',
    lcfg_member_tip:      '推しが出演時の追加加算',
    lcfg_w_priority:      'メンバー優先度重み',
    lcfg_w_fancount:      'ファン数重み',
    lcfg_frame_title:     '各会員枠倍率',
    lcfg_frame_tip:       '枠内観客の基本重み乗数（1–20倍）',
    lcfg_overflow_title:  '枠オーバーフロー設定',
    lcfg_overflow_label:  '枠オーバーフロー配分を許可',
    lcfg_overflow_tip:    'ある枠の応募者が席数に満たない場合、余剰席を一般枠へ自動配分します',

    // 执行抽选
    run_title:            '抽選実行',
    run_subtitle:         'RUN LOTTERY',
    run_applicants:       '応募者数',
    run_seats:            '総席数',
    run_frame_seats:      '会員枠席数',
    run_base_rate:        '基本当選率',
    run_confirm_title:    '公演情報確認',
    run_no_name:          '（未命名）',
    run_no_date:          '日付未設定',
    run_general:          '一般枠',
    run_issues_audiences: '観客データが空です',
    run_issues_capacity:  '公演席数が未設定です',
    run_start:            '▶ 抽選開始',
    run_result_title:     '抽選結果概要',
    run_winners:          '当選者数',
    run_losers:           '落選者数',
    run_rate:             '実際当選率',
    run_female_won:       '女性当選',
    run_frame_dist:       '枠別分布',
    run_member_dist:      '推し別分布（当選）',
    run_list_title:       '当選者リスト',
    run_list_tip:         '(先頭100件)',
    run_export_winners:   '当選CSVエクスポート',
    run_export_losers:    '落選CSVエクスポート',
    run_th_id:            'ID',
    run_th_frame:         '枠',
    run_th_gender_age:    '性別/年齢',
    run_th_member:        '会員',
    run_th_fav:           '推し',
    run_th_spend:         '消費',
    gender_male:          '男',
    gender_female:        '女',
    gender_other:         '他',
  },
};

// 当前语言，默认中文
let currentLang = localStorage.getItem('sim_lang') || 'zh';

// 取文字的快捷函数
function t(key) {
  return (I18N[currentLang] && I18N[currentLang][key]) || I18N['zh'][key] || key;
}